---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-operator
  namespace: openshift-operators
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "190"
    argocd.argoproj.io/sync-wave: "190"
spec:
  channel: {{ include "operator.channel" . | quote }}
  installPlanApproval: Automatic
  name: {{ include "operator.catalog-name" . }}
  source: {{ include "operator.source" . }}
  sourceNamespace: {{ include "operator.olm-namespace" . }}
