---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-operator
  namespace: openshift-operators
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "190"
    argocd.argoproj.io/sync-wave: "190"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: elasticsearch-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
