---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-operator
  namespace: openshift-operators
  labels:
    {{- include "operator.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "190"
    argocd.argoproj.io/sync-wave: "190"
spec:
  channel: "stable"
  installPlanApproval: Automatic
  name: jaeger-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
