{{- if and (eq (include "operator.cluster-type" .) "ocp4") .Values.createInstance }}
{{- $namespace := default "openshift-operators" .Values.namespaceInstance -}}
apiVersion: logging.openshift.io/v1
kind: Elasticsearch
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "300"
    helm.sh/hook-weight: "300"
  name: elasticsearch
  namespace: {{ $namespace }}
spec:
{{ .Values.spec | toYaml | indent 2 }}
{{- end -}}
