{{- if (and .Values.operatorNamespace (ne (include "operator.default-operator-namespace" .) .Values.operatorNamespace)) -}}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "100"
    helm.sh/hook-weight: "100"
  name: {{ include "operator.operator-namespace" . }}
{{- end -}}
