apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ include "operator.catalog-name" . }}
  namespace: {{ include "operator.operator-namespace" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "200"
    helm.sh/hook-weight: "200"
spec:
  channel: {{ include "operator.channel" . | quote }}
  installPlanApproval: Automatic
  name: {{ include "operator.catalog-name" . }}
  source: {{ include "operator.source" . }}
  sourceNamespace: {{ include "operator.olm-namespace" . }}
